# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eab52f82e78fc4ee2cbd8c57eb82a670e372b05e
      
      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775cbe2231b3c3f13471838de0b6
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@983d7736951b90b00b1afe09ec75844f7aee4d46
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@6673cd052c4cd6fcf4b4e6d7d86e0798fa12c9b3
        with:
          path: './dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164830504fb2b417f69f27fc9e2042d463
